<?php
    echo $this->testblocfunction();
    echo '<br />';
    $collection = $this->testproductfunction();
    foreach ($collection as $product) {
        echo $product->getId(); 
        echo ' = ';
        echo $product->getName(); //get name
        echo ' sku: ';
        echo $product->getSku();
        $stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($product->getId());
        echo ' qty: ';
        echo $stock->getQty();
        echo ' is in store: ';
        //echo $product->getStoreId(); //get store id
        $store = Mage::app()->getStore($product->getStoreId());
        echo $store->getName();
        echo '<br />';
    }
    echo '<br />';
    echo $this->getChildHtml('customer_form_register');
?>