<?php
$_submitmessageUrl = $this->getSubmitUrl();
//var_dump($_submitmessageUrl);
//var_dump(Mage::helper("adminhtml")->getUrl("*/*/csvformsubmit"));
?>
<div class="form-buttons">
    <form action="<?php echo $_submitmessageUrl; ?>" method="post" enctype="multipart/form-data" >
        <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
        <h3 class="icon-head head-prodquantities">Select CSV file to upload:</h3>
        <input type="file" name="file_csv" id="file_csv">
        <input type="submit" value="Upload CSV" name="submit" class="scallable" >
    </form>
</div>