<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:50%;"><h3 class="icon-head head-products"><?php echo $this->__('Manage Product Quantities') ?></h3></td>
        <td class="a-right">
            <?php echo $this->getButtonsHtml() ?>
        </td>
    </tr>
</table>
</div>
<?php echo $this->getChildHtml('warehousecsv_csvuploadform');?>
<div>
    <?php echo $this->getGridHtml() ?>
</div>